project:
  name: MyCloudFormation-Test-Project
  owner: your-email@example.com
  regions:
    - ap-southeast-1
  s3_bucket: taskcat-test-bucket-nhatthanh 

tests:
  default:
    template: ./Cloudformation/main.yml
    parameters:
      KeyName: my-aws-key 
      ImageId: ami-0435fcf800fb5418d
