project:
  name: MyCloudformationProject
  owner: your-email@example.com
  # Danh sách các Region kiểm thử template.
  regions:
    - ap-southeast-1
  s3_bucket: taskcat-test-bucket-nhatthanh

tests:
  default:
    template: ./Cloudformation/main.yml
    parameters:
      ProjectName: TaskcatTestRun
