version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing cfn-lint..."
      - pip install cfn-lint

  pre_build:
    commands:
      - echo "Running cfen-lint on all templates..."
      - cfn-lint ./Cloudformation/*.yml

  build:
    commands:
      - echo "Packaging CloudFormation templates..."
      - |
        aws cloudformation package \
          --template-file Cloudformation/main.yml \
          --s3-bucket taskcat-test-bucket-nhatthanh \
          --output-template-file packaged-template.yml

  post_build:
    commands:
      - echo "Packaging complete."

artifacts:
  files:
    - packaged-template.yml
