AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Template chính (root stack) để điều phối việc triển khai toàn bộ hạ tầng mạng và máy chủ.

Parameters:
  ProjectName:
    Type: String
    Description: Tên dự án
    Default: MyProject
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access.
  ImageId:
    Type: AWS::EC2::Image::Id
    Description: AMI ID for the EC2 instances.
    Default: ami-0c55b159cbfafe1f0

Resources:
  #Tạo VPC
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./vpc.yml
      Parameters:
        ProjectName: !Ref ProjectName

  #Tạo Security Groups
  SecurityGroupStack:
    Type: AWS::CloudFormation::Stack
    # Đảm bảo rằng Security Group chỉ được tạo sau khi đã tạo VPC
    Properties:
      TemplateURL: ./security_groups.yml
      Parameters:
        #Lấy giá trị VpcId từ Output của VPCStack và truyền vào
        MyHomeIP: 0.0.0.0/0
        VpcId: !GetAtt VPCStack.Outputs.MyVPC
        ProjectName: !Ref ProjectName

  #Tạo Route Tables
  RouteTableStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./route_table.yml
      Parameters:
        VpcId: !GetAtt VPCStack.Outputs.MyVPC
        # Giả sử cần ID của public/private subnet từ VPCStack
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnet
        PrivateSubnetId: !GetAtt VPCStack.Outputs.PrivateSubnet
        InternetGatewayId: !GetAtt VPCStack.Outputs.InternetGateway

  #Tạo NAT Gateway từ file nat_gateway.yml
  NatGatewayStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./nat_gateway.yml
      Parameters:
        PublicSubnetId: !GetAtt VPCStack.Outputs.PublicSubnet

  #Tạo EC2 trong Public Subnet
  EC2PublicStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./ec2_public.yml
      Parameters:
        KeyName: !Ref KeyName
        ImageId: !Ref ImageId
        InstanceType: t2.micro
        VpcId: !GetAtt VPCStack.Outputs.MyVPC
        SubnetId: !GetAtt VPCStack.Outputs.PublicSubnet
        # Lấy Security Group ID từ output của SecurityGroupStack
        SecurityGroupId: !GetAtt SecurityGroupStack.Outputs.PublicSecurityGroupId
